[package]
name = "ingot"
version = "0.1.0"
edition = "2021"

[features]
alloc = []
default = ["alloc", "ingot-types/alloc"]

[dependencies]
bitflags.workspace = true
ingot-macros.workspace = true
ingot-types.workspace = true
macaddr.workspace = true
zerocopy.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "modify"
harness = false
