[package]
name = "ingot"
version = "0.1.0"
edition = "2021"

[features]
alloc = []
default = ["alloc"]

[dependencies]
oxpacket-macros.workspace = true
pnet_packet.workspace = true
pnet_macros.workspace = true
pnet_macros_support.workspace = true