[package]
name = "ingot"
version = "0.1.0"
edition = "2021"

[features]
alloc = []
default = ["alloc"]

[dependencies]
bitflags.workspace = true
ingot-macros.workspace = true
ingot-types.workspace = true
macaddr.workspace = true
pnet_packet.workspace = true
pnet_macros.workspace = true
pnet_macros_support.workspace = true
zerocopy.workspace = true
