[package]
name = "ingot-types"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
alloc = []
default = ["alloc"]

[dependencies]
macaddr.workspace = true
pnet_macros_support.workspace = true
zerocopy.workspace = true
