[package]
name = "ingot-types"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
alloc = []
default = ["alloc"]

[dependencies]
ingot-macros.workspace = true
macaddr.workspace = true
zerocopy.workspace = true
